/**
 * Music genre detection & category definitions.
 *
 * Auto-categorises a track based on keywords found in its title/author.
 * Detection is intentionally best-effort — tracks that don't match any
 * known pattern fall into the "Others" bucket.
 */

export interface CategoryDef {
  slug: string;
  name: string;
  /** Lower-case keywords that trigger this category (OR match). */
  keywords: string[];
}

export const CATEGORIES: CategoryDef[] = [
  {
    slug: 'v-pop',
    name: 'V-Pop',
    keywords: [
      'sơn tùng',
      'm-tp',
      'hòa minzy',
      'jack',
      'j97',
      'binz',
      'karik',
      'tiên cookie',
      'tlinh',
      'pháo',
      'wowy',
      'den vâu',
      'soobin',
      'hương tràm',
      'chi pu',
      'đen',
      'min',
      'mỹ tâm',
      'hồ ngọc hà',
      'tuấn hưng',
      'đan trường',
      'vũ',
      'thịnh suy',
      'k-icm',
      'low g',
      'tăng duy tân',
      'erik',
      'only c',
      'bích phương',
      'huyền tâm môn',
      'mr siro',
      'khắc hưng',
      'hà anh tuấn',
      'đức phúc',
      'trọng hiếu',
      'andree',
    ],
  },
  {
    slug: 'k-pop',
    name: 'K-Pop',
    keywords: [
      'bts',
      'blackpink',
      'twice',
      'nct',
      'stray kids',
      'aespa',
      'ive',
      'newjeans',
      'le sserafim',
      'exo',
      'jennie',
      'lisa',
      'jisoo',
      'rose',
      'jungkook',
      'v bts',
      'jimin',
      'suga',
      'rm',
      'j-hope',
      'seventeen',
      'treasure',
      'ateez',
      'itzy',
      'gidle',
      'txt',
      'enhypen',
      'babymonster',
      'red velvet',
      'shinee',
      'super junior',
      'girls generation',
      'snsd',
      '2ne1',
      'bigbang',
      'ikon',
      'winner',
      'psy',
      'g dragon',
      'taeyang',
      'iu',
      'chungha',
      'sunmi',
      'taeyeon',
      'hyuna',
      'boa',
      'kpop',
      'k-pop',
    ],
  },
  {
    slug: 'rap',
    name: 'Rap / Hip-Hop',
    keywords: [
      'rap',
      'hip hop',
      'hip-hop',
      'trap',
      'drill',
      'freestyle',
      'beef',
      'diss',
      'flow',
      'bars',
      'mc',
      'lil',
      'drake',
      'kendrick',
      'kanye',
      'travis scott',
      '21 savage',
      'migos',
      'future',
      'metro boomin',
      'juice wrld',
      'xxx',
      'pop smoke',
      'cardi b',
      'nicki minaj',
      'megan thee',
      'eminem',
      'snoop dogg',
      '50 cent',
      'jay-z',
      'notorious',
      'tupac',
      'nas',
      'mf doom',
      'tyler the creator',
      'asap rocky',
      'cole',
      'logic',
      'dababy',
      'gunna',
      'lil baby',
      'youngboy',
      'thugger',
      'offset',
      'quavo',
      'takeoff',
      'den vâu',
      'karik',
      'binz',
      'tlinh',
      'suboi',
      'wowy',
      'rhymastic',
      '16 typh',
      'tiến triệu',
    ],
  },
  {
    slug: 'edm',
    name: 'EDM / Electronic',
    keywords: [
      'edm',
      'electronic',
      'dubstep',
      'house',
      'techno',
      'trance',
      'drum and bass',
      'dnb',
      'd&b',
      'hardstyle',
      'future bass',
      'bass drop',
      'drop',
      'remix',
      'dj',
      'avicii',
      'marshmello',
      'martin garrix',
      'calvin harris',
      'kygo',
      'zedd',
      'skrillex',
      'deadmau5',
      'tiësto',
      'tiesto',
      'david guetta',
      'alan walker',
      'illenium',
      'flume',
      'odesza',
      'chainsmokers',
      'mellow',
      'electro',
      'synth',
      'cyberpunk',
      'nightcore',
      'phonk',
      'slowed',
      'reverb',
    ],
  },
  {
    slug: 'rock',
    name: 'Rock',
    keywords: [
      'rock',
      'alternative',
      'indie rock',
      'punk',
      'grunge',
      'metal',
      'heavy metal',
      'hard rock',
      'emo',
      'post-rock',
      'shoegaze',
      'nirvana',
      'foo fighters',
      'radiohead',
      'coldplay',
      'queen',
      'acdc',
      'ac/dc',
      'led zeppelin',
      'pink floyd',
      'metallica',
      'linkin park',
      'green day',
      'red hot chili',
      'system of a down',
      'slipknot',
      'imagine dragons',
      'paramore',
      'my chemical romance',
      'artic monkeys',
      'arctic monkeys',
      'the beatles',
      'rolling stones',
      'guitar',
      'riff',
      'bố già',
      'bức tường',
      'ngũ cung',
    ],
  },
  {
    slug: 'r&b',
    name: 'R&B / Soul',
    keywords: [
      'rnb',
      'r&b',
      'soul',
      'neo soul',
      'funk',
      'groove',
      'the weeknd',
      'frank ocean',
      'sza',
      'brent faiyaz',
      'daniel caesar',
      'steve lacy',
      'snoh aalegra',
      'jhené aiko',
      'jhene aiko',
      'bryson tiller',
      '6lack',
      'tory lanez',
      'chris brown',
      'usher',
      'alicia keys',
      'beyoncé',
      'beyonce',
      'rihanna',
      'bruno mars',
      'anderson paak',
      'h.e.r.',
      'masego',
      'tone stith',
      'rvssian',
    ],
  },
  {
    slug: 'lofi',
    name: 'Lo-fi / Chill',
    keywords: [
      'lofi',
      'lo-fi',
      'chill',
      'chillhop',
      'lofi hip hop',
      'studying',
      'relax',
      'calm',
      'peaceful',
      'ambient',
      'sleep',
      'rain',
      'coffee',
      'jazzhop',
      'beats to',
      'lofi girl',
      'dreamy',
      'vaporwave',
      'chillout',
      'study music',
      'focus',
      'lazy',
      'slow',
      'mood',
    ],
  },
  {
    slug: 'ballad',
    name: 'Ballad / Acoustic',
    keywords: [
      'ballad',
      'ballad',
      'acoustic',
      'piano',
      'sad',
      'love song',
      'tình ca',
      'tình yêu',
      'emotional',
      'acoustic cover',
      'stripped',
      'unplugged',
      'slow rock',
      'lời ru',
      'solo acoustic',
      'fingerstyle',
      'ukulele',
      'guitar acoustic',
    ],
  },
  {
    slug: 'jazz',
    name: 'Jazz / Blues',
    keywords: [
      'jazz',
      'blues',
      'swing',
      'bebop',
      'bossa nova',
      'samba',
      'latin jazz',
      'smooth jazz',
      'fusion',
      'jazz band',
      'brass',
      'saxophone',
      'trumpet',
      'bluegrass',
      'blues rock',
      'delta blues',
      'chicago blues',
    ],
  },
  {
    slug: 'pop',
    name: 'Pop',
    keywords: [
      'pop',
      'taylor swift',
      'ariana grande',
      'billie eilish',
      'olivia rodrigo',
      'dua lipa',
      'harry styles',
      'ed sheeran',
      'justin bieber',
      'selena gomez',
      'miley cyrus',
      'lady gaga',
      'katy perry',
      'shakira',
      'p!nk',
      'adele',
      'sam smith',
      'charlie puth',
      'shawn mendes',
      'camila cabello',
      'halsey',
      'demi lovato',
      'doja cat',
      'sabrina carpenter',
      'chappell roan',
      'tate mcrae',
      'conan gray',
      'lana del rey',
      'maroon 5',
      'one direction',
      'backstreet',
      'nsync',
      'britney',
      'christina',
      'madonna',
      'michael jackson',
      'elvis',
      'teen pop',
      'pov',
      'viral',
    ],
  },
  {
    slug: 'indie',
    name: 'Indie',
    keywords: [
      'indie',
      'bedroom pop',
      'dream pop',
      'indie folk',
      'folk',
      'singer songwriter',
      'tame impala',
      'mac demarco',
      'beach house',
      'vampire weekend',
      'bon iver',
      'phoebe bridgers',
      'mitski',
      'clairo',
      'rex orange county',
      'still woozy',
      'wallows',
      'dayglow',
      'boy pablo',
      'men i trust',
      'cuco',
      'japanese breakfast',
      'alex g',
      'elliott smith',
      'sufjan stevens',
      'iron & wine',
      'the nbhd',
      'the neighbourhood',
      'glass animals',
      'alt-j',
      'alt j',
    ],
  },
  {
    slug: 'bolero',
    name: 'Bolero / Trữ tình',
    keywords: [
      'bolero',
      'trữ tình',
      'nhạc vàng',
      'cải lương',
      'dân ca',
      'quê hương',
      'phi nhung',
      'đàm vĩnh hưng',
      'minh tuyết',
      'lệ quyên',
      'mạnh quỳnh',
      'nhật kim anh',
      'đan nguyên',
      'giao linh',
      'quang lê',
      'ngọc sơn',
      'hoài linh',
      'hương lan',
      'dương hồng loan',
      'chế thanh',
      'trường vũ',
      'phi điệp',
      'cẩm ly',
      'lệ thu',
      'sơn ca',
    ],
  },
  {
    slug: 'country',
    name: 'Country',
    keywords: [
      'country',
      'country music',
      'country pop',
      'outlaw',
      'americana',
      'luke combs',
      'morgan wallen',
      'chris stapleton',
      'kacey musgraves',
      'johnny cash',
      'dolly parton',
      'willie nelson',
      'garth brooks',
      'tim mcgraw',
      'faith hill',
      'carrie underwood',
      'blake shelton',
      'keith urban',
      'taylor swift country',
      'zach bryan',
      'tyler childers',
    ],
  },
  {
    slug: 'classical',
    name: 'Classical / Instrumental',
    keywords: [
      'classical',
      'orchestra',
      'symphony',
      'sonata',
      'concerto',
      'instrumental',
      'piano solo',
      'violin',
      'cello',
      'classic music',
      'mozart',
      'beethoven',
      'bach',
      'chopin',
      'vivaldi',
      'tchaikovsky',
      'debussy',
      'satie',
      'liszt',
      'schubert',
      'brahms',
      'wagner',
      'film score',
      'soundtrack epic',
      'cinematic',
    ],
  },
];

/** Default category for tracks that don't match any keyword. */
export const DEFAULT_CATEGORY = 'others';

/** Get a category slug from track title/author. */
export function detectCategory(title: string, author: string): string {
  const text = `${title} ${author}`.toLowerCase();
  for (const cat of CATEGORIES) {
    if (cat.keywords.some((kw) => text.includes(kw))) return cat.slug;
  }
  return DEFAULT_CATEGORY;
}

/** Look up a category definition by slug. */
export function getCategory(slug: string): CategoryDef | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

/** Map slugs to human-readable names (with a localized fallback). */
export function categoryName(slug: string): string {
  return getCategory(slug)?.name ?? 'Khác';
}
